package com.team_3.School_Medical_Management_System.DTO;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class HealthCheck_StudentCreateDTO {
    // No checkID field - will be auto-generated by database
    private Integer studentID;
    private String status;       // Thêm trường status
    private float height;
    private float weight;
    private String visionLeft;
    private String visionRight;
    private String hearing;
    private String dentalCheck;
    private String temperature;
    private float bmi;
    private String overallResult;

    // Added field for tracking the nurse who created the record

    private Integer CreatedByNurseID;
    private String createdByNurseName;
}
