package com.team_3.School_Medical_Management_System.InterFaceSerivceInterFace;

import com.team_3.School_Medical_Management_System.DTO.Post_vaccination_observationsDTO;
import com.team_3.School_Medical_Management_System.DTO.Post_vaccination_observations_SendForParent_DTO;
import com.team_3.School_Medical_Management_System.DTO.Post_vaccination_observations_edit_DTO;
import com.team_3.School_Medical_Management_System.DTO.Post_vaccination_observations_edit_Update_SendParent_DTO;
import com.team_3.School_Medical_Management_System.Model.Post_vaccination_observations;

import java.util.List;

public interface Post_vaccination_observationsServiceInterFace {
    public List<Post_vaccination_observationsDTO> getPost_vaccination_observations();
    public Post_vaccination_observationsDTO getPost_vaccination_observation(Integer id);
    public Post_vaccination_observationsDTO addPost_vaccination_observation(Post_vaccination_observationsDTO dto);
    public Post_vaccination_observations_edit_DTO updatePost_vaccination_observation(Post_vaccination_observations_edit_DTO dto);
    public Post_vaccination_observations_SendForParent_DTO addPost_vaccination_observationByEmail(Post_vaccination_observations_SendForParent_DTO entity);
    public Post_vaccination_observations_edit_Update_SendParent_DTO updateAndResendEmail(Integer recordId, Post_vaccination_observations_edit_Update_SendParent_DTO dto);
}
